Yes: No more bug ! (as we know yet ... ;)

diff --git a/bin/pgpid-qrscan b/bin/pgpid-qrscan
--- a/bin/pgpid-qrscan
+++ b/bin/pgpid-qrscan
@@ -58,6 +58,7 @@ $PGPI_NAME scan QRcodes containing parts of OpenPGP secrets from IMAGES or webca
 and import this secrets into a factory reseted OpenPGP secured device (eg yubikey)."
 
 	soptions="
+    -k, --no-send            don't send public key (certificate) to HKPS keyserver ($HKPSSERVER)
     -v, --verbose            increase log verbosity: ...<notice[5]<info[6]<debug[7]  (current: $LOGLEVEL)
     -q, --quiet              decrease log verbosity: ...<err[3]<warning[4]<notice[5]<...  (current: $LOGLEVEL)
     -h, --help               show this help and exit
@@ -85,8 +86,11 @@ helpmsg="$usage
 Options: $soptions
 "
 
+nosend=""
+
 for ((i=0;$#;)) ; do
 case "$1" in
+    -k|--no-send) nosend="true" ;;
 	-l|--log-l*) shift ; LOGLEVEL="$1" ; [[ "$LOGLEVEL" == [0-9] ]] || { echo -e "Error: log-level out of range [0-7]" >&2 ; $_exit 2 ; } ;;
 	-L|--log-e*) shift ; LOGEXITPRIO="$1"
 		grep -q "\<$LOGEXITPRIO\>" <<<${!loglevels[@]} || { echo -e "Error: log-exit \"$LOGEXITPRIO\" is none of: ${!loglevels[@]}" >&2 ; $_exit 2 ; } ;;
@@ -129,6 +133,21 @@ chmod -R go-rwx "$TMPDIR"
 ### Run ###
 
 FPR=$(bl_qrkey_scan --workdir "$TMPDIR" --homedir "$TMPDIR/gnupg" "$@")
+
+# If we fail testing no passphrase, there is one. Then we will remove it, because it is just a pain in the ass for the last operations
+if ! gpg --homedir "$TMPDIR/gnupg" --batch --pinentry-mode loopback --passphrase "" --dry-run --change-passphrase "$FPR" 2> >(bl_log debug) ; then
+	if [[ -f "$TMPDIR/passphrase" ]] ; then
+		read passphrase < "$TMPDIR/passphrase"
+	else
+		for ((i=1;i<=3;i++)) ; do
+			passphrase=$(bl_input --password --text "(To put secret keys on security tocken)" "Passphrase")
+			if echo "$passphrase" | gpg --homedir "$TMPDIR/gnupg" --command-fd 0 --batch --pinentry-mode loopback --dry-run --change-passphrase "$FPR" 2> >(grep -i -m1 pass | bl_log notice) ; then
+				break
+			fi
+		done
+	fi
+	bl_qrkey_change_passphrase --homedir "$TMPDIR/gnupg" --passfrom /dev/stdin --newpassphrase "" "$FPR" <<<"$passphrase" > >(bl_log notice) 2>&1
+fi
 
 # get some info
 uids=$(gpg --quiet --homedir "$TMPDIR/gnupg" --list-keys "$FPR" 2> >(bl_log warning) | grep "^uid")
@@ -174,7 +193,6 @@ quit" | gpg --homedir "$TMPDIR/gnupg" --command-fd 0 --batch --with-colons --pin
 #quit" | gpg --homedir "$TMPDIR/gnupg" --command-fd 0 --batch --with-colons --pinentry-mode loopback --passphrase "12345678" --card-edit 1> >(bl_log debug) 2>&1 || bl_log crit "Setting Pubkey URL in OpenPGP card FAIL ($?)"
 
 bl_log notice "Unfortunately, we can't automatize moving key to card, then you should move keys master 1 and 2 manualy..."
-bl_qrkey_change_passphrase --homedir "$TMPDIR/gnupg" --passfrom /dev/stdin --newpassphrase "" "$FPR" < "$TMPDIR/passphrase" > >(bl_log notice) 2>&1 || return $?
 bl_log notice "Note: passphrase has been removed to ease this manual operation, but admin PIN can't and is the default '12345678'."
 #printf "${passphrase[*]}\nm\n" | gpg --homedir "$TMPDIR/gnupg" --command-fd 0 --batch --pinentry-mode loopback --change-passphrase ${FPRS[0]} 1> >(bl_log notice) 2>&1 || true
 gpg --homedir "$TMPDIR/gnupg" --edit-key "${FPR}" || bl_log warning "Moving OpenPGP keys to card returns $?"
@@ -189,7 +207,7 @@ gpg --homedir "$TMPDIR/gnupg" --edit-key "${FPR}" || bl_log warning "Moving Open
 #done < <(gpg --homedir "$TMPDIR/gnupg" --card-status --with-colons)
 #PGPID[card$i]="$(declare -p OPGPCARD)"
 
-if ! gpg --homedir "$TMPDIR/gnupg" --keyserver "${HKPSSERVER}" --send-keys "$FPR" ; then
+if [[ "$nosend" ]] || ! gpg --homedir "$TMPDIR/gnupg" --keyserver "${HKPSSERVER}" --send-keys "$FPR" ; then
 	gpg --homedir "$TMPDIR/gnupg" --export --armor "$FPR"
 	bl_log warning "Please send, as soon as possible, this PGP public key to the hkp keyserver '${HKPSSERVER}'."
 fi
