bugfixs in pl-log bash library + make pgpi use it

diff --git a/pgpi b/pgpi
--- a/pgpi
+++ b/pgpi
@@ -42,6 +42,7 @@ fi
 PGPI_NAME="$(basename $(readlink -f "$BASH_SOURCE") )"
 PGPI_VERSION="0.0.1"
 
+
 ### Constants ###
 
 FACE_MARGIN_WIDTH="25/100"
@@ -49,28 +50,13 @@ FACE_MARGIN_HEIGHT="50/100"
 TESSDATADIR="$(dirname "$0")/data/"
 GEOLIST_CENTROID="$(dirname "$0")/data/geolist_centroid.txt"
 
-declare -A loglevels=(
-[emerg]=0
-[alert]=1
-[crit]=2
-[error]=3 # deprecated synonym for err
-[err]=3
-[warning]=4
-[notice]=5
-[info]=6
-[debug]=7)
-
-declare -a logcolors=(47 45 41 31 35 33 36 37)
-
 ### Default option values ###
-
-PGPI_LOGCMD="_log -Q"
 
 if [[ "$BASH_SOURCE" == "$0" ]] ; then
 	# run as a program
 	set -e
 	# set global constants real constant (read only)
-	declare -r FACE_MARGIN_WIDTH FACE_MARGIN_HEIGHT TESSDATADIR GEOLIST_CENTROID loglevels logcolors
+	declare -r FACE_MARGIN_WIDTH FACE_MARGIN_HEIGHT TESSDATADIR GEOLIST_CENTROID
 	_exit="exit"
 	LOGEXITPRIO=crit
 	LOGLEVEL=5
@@ -111,7 +97,6 @@ helpmsg="$usage
 
 Options:
     -L, --log-exit PRIORITY  log exit priority: emerg|alert|crit|err|warning|... (current: $LOGEXITPRIO )
-    -s, --syslog             write also logs to the system logs
 $soptions
 "
 
@@ -123,7 +108,6 @@ case "$1" in
 		grep -q "\<$LOGEXITPRIO\>" <<<${!loglevels[@]} || { echo -e "Error: log-exit \"$LOGEXITPRIO\" is none of: ${!loglevels[@]}" >&2 ; $_exit 2 ; } ;;
 	-v|--verb*) ((LOGLEVEL++)) ;;
 	-q|--quiet) ((LOGLEVEL--)) ;;
-	-s|--syslog) PGPI_LOGCMD="_log" ;;
 	-j|--json) PGPI_OUTPUTJSON=true ;;
 	-H|--hurry) PGPI_INTERACTIVE=false ;;
 	-h|--h*) echo "$helpmsg" ; $_exit ;;
@@ -138,81 +122,7 @@ done
 
 ### functions ###
 
-_log() {
-	local helpmsg="Usage: $FUNCNAME [OPTIONS]... PRIORITY [MESSAGE]...
-PRIORITY list: $(declare -p loglevels)
-If level[PRIORITY] is under LOGLEVEL=$LOGLEVEL, don't log anything.
-If PRIORITY is more serious than LOGEXITPRIO=$LOGEXITPRIO, exit(8+level[PRIORITY])
-If there is no MESSAGE in command line, read it from stdin.
-
-$FUNCNAME specific options:
- -q, --quiet              do not output message to standard error
- -Q, --no-act             do not send message to the logs system (syslog)
-     --color[=<on|off|auto>]
-                          colorize messages sent to standard error (default: auto)
-
-Options forwarded to 'logger':
- -f, --file <file>        log the contents of this file
- -e, --skip-empty         do not log empty lines when processing files
-     --octet-count        use rfc6587 octet counting
-     --prio-prefix        look for a prefix on every line read from stdin
- -S, --size <size>        maximum size for a single message
- -n, --server <name>      write to this remote syslog server
- -P, --port <port>        use this port for UDP or TCP connection
- -T, --tcp                use TCP only
- -d, --udp                use UDP only
-     --rfc3164            use the obsolete BSD syslog protocol
-     --rfc5424[=<snip>]   use the syslog protocol (the default for remote);
-                            <snip> can be notime, or notq, and/or nohost
-     --sd-id <id>         rfc5424 structured data ID
-     --sd-param <data>    rfc5424 structured data name=value
-     --msgid <msgid>      set rfc5424 message id field
- -u, --socket <socket>    write to this Unix socket
-     --socket-errors[=<on|off|auto>]
-                          print connection errors when using Unix sockets
-     --journald[=<file>]  write journald entry
-"
-	local stderr="--stderr" no_act logger_options color="auto"
-	for ((;$#;)) ; do
-		case "$1" in
-			-q|--quiet) unset stderr ;;
-			-Q|--no-act) no_act="--no-act" ;;
-			--color|--color=on) color=on ;;
-			--color=off) color=off ;;
-			--color=auto) color=auto ;;
-			-e|--skip-empty|--octet-count|--prio-prefix|-T|--tcp|-d|--udp|--rfc3164)
-				logger_options+=("$1") ;;
-			-f|--file|-S|--size|-n|--server|-P|--port|--sd-id|--sd-param|--msgid|-u|--socket)
-				logger_options+=("$1")
-				shift
-				logger_options+=("$1") ;;
-			--rfc5424*|--socket-errors*|--journald*)
-				logger_options+=("$1") ;;
-			-h|--help) echo "$helpmsg" ; return ;;
-			-V|--version) echo "$FUNCNAME $PGPI_VERSION" ; return ;;
-			--) shift ; break ;;
-			-*) echo -e "$FUNCNAME: Error: Unrecognized option/parameters $1\n$helpmsg" >&2 ; return 2 ;;
-			*) break ;;
-		esac
-		shift
-	done
-
-	local priority=$1 filter
-	shift
-	local llevel=${loglevels[$priority]}
-	if ((llevel > $LOGLEVEL)) ; then
-		# If there is no MESSAGE, purge stdin; else do nothing.
-		[[ "$@" ]] || cat >/dev/null
-	else
-		if [[ "$color" == on ]] || [[ "$color" == auto ]] && [[ -t 2 ]] ; then
-			filter="2> >(sed 's,: ,: \x1b[${logcolors[$llevel]}m${priority}:\x1b[0m ,' >&2)"
-		else
-			filter="2> >(sed 's,: ,: ${priority}: ,' >&2)"
-		fi
-		eval 'logger -p "$priority" $stderr $no_act "${logger_options[@]}" --id=$$ --tag "${0##*/}" -- "$@"' "$filter"
-	fi
-	((llevel > loglevels[$LOGEXITPRIO] )) || exit $((8+llevel))
-}
+. pl-log --no-act --log-level "$LOGLEVEL" --log-exit "$LOGEXITPRIO"
 
 mrz_checkdigit() {
 	local helpmsg="Usage: $FUNCNAME STRING [EXPECTED_RESULT]
@@ -264,15 +174,15 @@ Analyse a Machine Readable Zone and fill the associative array named AANAME"
 	shift
 	local ch mrz=("$@")
 
-	$PGPI_LOGCMD debug "mrz[0]= \"${mrz[0]}\""
+	pl_log debug "mrz[0]= \"${mrz[0]}\""
 	if [[ ${mrz[0]:0:1} != P ]] ; then
-		$PGPI_LOGCMD debug "mrz[0]= \"${mrz[0]}\""
-		$PGPI_LOGCMD warning "$FUNCNAME: unsupported. (not an ISO/IEC 7501-1 passport)"
+		pl_log debug "mrz[0]= \"${mrz[0]}\""
+		pl_log warning "$FUNCNAME: unsupported. (not an ISO/IEC 7501-1 passport)"
 		return 1
 	fi
-	$PGPI_LOGCMD debug "mrz[1]= \"${mrz[1]}\""
+	pl_log debug "mrz[1]= \"${mrz[1]}\""
 	if [[ ${#mrz[0]} != 44 ]] || [[ ${#mrz[1]} != 44 ]] ; then
-		$PGPI_LOGCMD warning "$FUNCNAME: Invalid MRZ lenght ${#mrz[0]} ${#mrz[1]}"
+		pl_log warning "$FUNCNAME: Invalid MRZ lenght ${#mrz[0]} ${#mrz[1]}"
 		return 2
 	fi
 
@@ -297,7 +207,7 @@ Analyse a Machine Readable Zone and fill the associative array named AANAME"
 	for ch in number date_of_birth expiration_date personal_number composite ; do
 		doc[checked_$ch]=$(mrz_checkdigit "${doc[$ch]}")
 		doc[valid_$ch]=$( [[ ${doc[checked_$ch]} == ${doc[check_$ch]} ]] && echo true || echo false )
-		${doc[valid_$ch]} || $PGPI_LOGCMD warning "OBI WAN KENOBI ??? $ch checksum -> ${doc[check_$ch]}. Should be ${doc[checked_$ch]}."
+		${doc[valid_$ch]} || pl_log warning "OBI WAN KENOBI ??? $ch checksum -> ${doc[check_$ch]}. Should be ${doc[checked_$ch]}."
 	done
 
 	doc[names]=$(echo $(echo "${doc[all_names]#*<<}" | tr '<' ' ') )
@@ -327,7 +237,7 @@ Parameters:
 			sname=$(sed 's,[ ;,<-]\+,<,g'<<<"$1" )
 			sname="${sname^^}"
 			if ! [[ "$sname" =~ ^[A-Z'<']+$ ]] ; then
-				$PGPI_LOGCMD err "$FUNCNAME: only [A-Z] characters allowed in $1"
+				pl_log err "$FUNCNAME: only [A-Z] characters allowed in $1"
 				return 1
 			fi ;;
 		-g|--g*)
@@ -335,28 +245,28 @@ Parameters:
 			gname=$(sed 's,[ ;,<-]\+,<,g'<<<"$1" )
 			gname="${gname^^}<<"
 			if ! [[ "$gname" =~ ^[A-Z'<']+$ ]] ; then
-				$PGPI_LOGCMD err "$FUNCNAME: only [A-Z] characters allowed in $1"
+				pl_log err "$FUNCNAME: only [A-Z] characters allowed in $1"
 				return 1
 			fi ;;
 		-d|--birth-d*)
 			shift
 			if ((${#1}<8)) ; then
 				bdate="$(($(date +"%y%m%d") < $1 ? 19 : 20))$1"
-				$PGPI_LOGCMD notice "$FUNCNAME: birth date '$1' is too short, assuming $bdate."
+				pl_log notice "$FUNCNAME: birth date '$1' is too short, assuming $bdate."
 			else
 				bdate=$1
 			fi
 			if ! tohash2=$(date --date "$bdate" +"%Y-%m-%d" ) ; then
-				$PGPI_LOGCMD err "$FUNCNAME: can't reformart birthdate $date"
+				pl_log err "$FUNCNAME: can't reformart birthdate $date"
 				return 2
 			fi ;;
 		-c|--birth-c*)
 			shift
 			if ! read c iso cname < <(grep "	$1	" "$GEOLIST_CENTROID") ; then
-				$PGPI_LOGCMD err "$FUNCNAME: no \"$1\" in $GEOLIST_CENTROID"
+				pl_log err "$FUNCNAME: no \"$1\" in $GEOLIST_CENTROID"
 				return 3
 			fi
-			$PGPI_LOGCMD debug "$FUNCNAME: $c $iso $cname" ;;
+			pl_log debug "$FUNCNAME: $c $iso $cname" ;;
 		-p|--birth-p*)
 			shift
 			#TODO: check if coordinate is valid (cf. Specifications)
@@ -367,11 +277,11 @@ Parameters:
 	done
 	[[ "$mrzn" ]] || mrzn="${sname}<<$gname"
 	if ! tohash1=$(grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"$mrzn" ) ; then
-		$PGPI_LOGCMD err "$FUNCNAME: no complete surname and given names extracted from $mrzn"
+		pl_log err "$FUNCNAME: no complete surname and given names extracted from $mrzn"
 		return 1
 	fi
-	$PGPI_LOGCMD debug "$FUNCNAME: names: $tohash1"
-	$PGPI_LOGCMD debug "$FUNCNAME: birthdate: $tohash2"
+	pl_log debug "$FUNCNAME: names: $tohash1"
+	pl_log debug "$FUNCNAME: birthdate: $tohash2"
 	echo "$(printf "$tohash1$tohash2" | md5sum | xxd -r -p | basenc --base64url | sed 's/==$//')$c"
 }
 
@@ -465,6 +375,7 @@ _chooseinlist() {
 	return $ret
 }
 
+
 # Do nothing else if sourced
 [[ "$BASH_SOURCE" == "$0" ]] || return 0
 
@@ -472,7 +383,7 @@ _chooseinlist() {
 ### Init ###
 
 #_onexit() {
-#	[[ -d "$TMPDIR" ]] && rm -rvf "$TMPDIR" | $PGPI_LOGCMD info
+#	[[ -d "$TMPDIR" ]] && rm -rvf "$TMPDIR" | pl_log info
 #}
 #
 #TMPDIR=$(mktemp -d -t "$PGPI_NAME".XXXXXX) || log crit "crit: Can not create a safe temporary directory."
@@ -490,35 +401,34 @@ while [[ "$1" ]] ; do
 	shift
 
 
-	facep=$(facedetect --best -- "$f" 2> >($PGPI_LOGCMD notice) || true )
+	facep=$(facedetect --best -- "$f" 2> >(pl_log notice) || true )
 	if ! [[ "$facep" ]] ; then
-		$PGPI_LOGCMD err "Error: No face detected in $f"
+		pl_log err "Error: No face detected in $f"
 		continue
 	fi
 	read px py sx sy etc <<<"$facep"
 	mx=$((sx*$FACE_MARGIN_WIDTH))
 	my=$((sy*$FACE_MARGIN_HEIGHT))
-	$PGPI_LOGCMD info "$f face -> position: +$px+$py  size: ${sx}x$sy  marges: +${mx}+$my"
+	pl_log info "$f face -> position: +$px+$py  size: ${sx}x$sy  marges: +${mx}+$my"
 
-
-	if ! mrz=($(gm convert -crop +0+$((py+sy+my)) "$f" - 2> >($PGPI_LOGCMD notice) | tesseract --tessdata-dir "$TESSDATADIR" -l mrz - - 2> >($PGPI_LOGCMD notice) | sed 's/[^0-9A-Z<]*//g' | grep -m1 -A2 "<<")) ; then
-		$PGPI_LOGCMD err "$f: No machine-readable zone detected"
+	if ! mrz=($(gm convert -crop +0+$((py+sy+my)) "$f" - 2> >(pl_log notice) | tesseract --tessdata-dir "$TESSDATADIR" -l mrz - - 2> >(pl_log notice) | sed 's/[^0-9A-Z<]*//g' | grep -m1 -A2 "<<")) ; then
+		pl_log err "$f: No machine-readable zone detected"
 		continue
 	fi
 
 	declare -A DOCUMENT=()
 	if ! mrz_analyse DOCUMENT "${mrz[@]}" ; then
-		$PGPI_LOGCMD err "$f: Invalid or unsupported machine-readable zone"
+		pl_log err "$f: Invalid or unsupported machine-readable zone"
 		continue
 	fi
 
 	DOCUMENT[filename]=$f
-	DOCUMENT[face_scan_64url]=$(gm convert -crop $((sx+mx))x$((sy+my))+$((px-(mx/2)))+$((py-(my/2))) "$f" jpeg:- 2> >($PGPI_LOGCMD warning) | basenc --base64url --wrap 0 )
+	DOCUMENT[face_scan_64url]=$(gm convert -crop $((sx+mx))x$((sy+my))+$((px-(mx/2)))+$((py-(my/2))) "$f" jpeg:- 2> >(pl_log warning) | basenc --base64url --wrap 0 )
 	if ((${#DOCUMENT[face_scan_64url]} < 2048 )) ; then
-		$PGPI_LOGCMD warning "$outdir/face.jpg: too small (${#DOCUMENT[face_scan_64url]} < 2048)"
+		pl_log warning "$outdir/face.jpg: too small (${#DOCUMENT[face_scan_64url]} < 2048)"
 		unset DOCUMENT[face_scan_64url]
 	elif ((${#DOCUMENT[face_scan_64url]} > (1<<16) )) ; then
-		$PGPI_LOGCMD warning "$outdir/face.jpg: too big (${#DOCUMENT[face_scan_64url]} > $((1<<16)))"
+		pl_log warning "$outdir/face.jpg: too big (${#DOCUMENT[face_scan_64url]} > $((1<<16)))"
 		unset DOCUMENT[face_scan_64url]
 	fi
 
@@ -529,7 +439,7 @@ while [[ "$1" ]] ; do
 	#         * Year of birth date is not written with 4 digit (and people may live longer than 100 years)
 	#         * Humans may have done error on birth date, surname or given names.
 	if ! DOCUMENT[udid4_auto]=$(pgpi_gen_udid4 --mrz-names "${DOCUMENT[all_names]}" --birth-date "${DOCUMENT[date_of_birth]}" --birth-country "${DOCUMENT[nationality]}") ; then
-		$PGPI_LOGCMD warning "can't generate an udid4 from mrz data"
+		pl_log warning "can't generate an udid4 from mrz data"
 		unset DOCUMENT[udid4_auto]
 	fi
 
@@ -560,7 +470,7 @@ Country of birth: ${country_of_birth:=${DOCUMENT[nationality]}}
 			esac
 		done
 		if ! DOCUMENT[udid4]=$(pgpi_gen_udid4 --surname "$surname" --given-names "$names" --birth-date "$date_of_birth" --birth-country "$country_of_birth") ; then
-			$PGPI_LOGCMD error "can't generate an udid4 from data you have validated"
+			pl_log error "can't generate an udid4 from data you have validated"
 			unset DOCUMENT[udid4]
 		fi
 	fi
@@ -570,13 +480,13 @@ Country of birth: ${country_of_birth:=${DOCUMENT[nationality]}}
 		continue
 	fi
 
-	#for i in "${!DOCUMENT[@]}"; do printf "[$i] -> ${DOCUMENT[$i]}\n"; done | $PGPI_LOGCMD debug
+	#for i in "${!DOCUMENT[@]}"; do printf "[$i] -> ${DOCUMENT[$i]}\n"; done | pl_log debug
 
 	outdir="$PGPI_OUTPATH/${mrz[0]//</_}"
 	mkdir -p "$outdir"
 
-	cp -bvf "$f" "$outdir/document.orig" 2> >($PGPI_LOGCMD warning) | $PGPI_LOGCMD info
-	pgpi_var_to_json DOCUMENT > "$outdir/document.json" 2> >($PGPI_LOGCMD crit)
+	cp -bvf "$f" "$outdir/document.orig" 2> >(pl_log warning) | pl_log info
+	pgpi_var_to_json DOCUMENT > "$outdir/document.json" 2> >(pl_log crit)
 done
 
 exit 0
